# Generated by Django 3.1 on 2020-08-13 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdbapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servernetwork',
            old_name='host',
            new_name='server',
        ),
        migrations.AddField(
            model_name='idc',
            name='desc',
            field=models.CharField(max_length=64, null=True, verbose_name='描述信息'),
        ),
        migrations.AddField(
            model_name='idc',
            name='floor',
            field=models.IntegerField(default=1, null=True, verbose_name='楼层'),
        ),
        migrations.AddField(
            model_name='idc',
            name='region',
            field=models.CharField(max_length=64, null=True, verbose_name='区域'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=32, null=True, verbose_name='部门名称'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='address',
            field=models.CharField(max_length=32, null=True, verbose_name='IDC地址'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='name',
            field=models.CharField(max_length=32, null=True, verbose_name='IDC名称'),
        ),
        migrations.AlterField(
            model_name='servernetwork',
            name='interface',
            field=models.CharField(max_length=32, null=True, verbose_name='网卡名'),
        ),
        migrations.CreateModel(
            name='HandleLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='变更记录')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('servers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdbapi.server')),
            ],
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='磁盘名')),
                ('slot', models.CharField(blank=True, max_length=32, null=True, verbose_name='插槽位')),
                ('model', models.CharField(blank=True, max_length=128, null=True, verbose_name='磁盘型号')),
                ('capacity', models.FloatField(blank=True, null=True, verbose_name='磁盘容量GB')),
                ('pd_type', models.CharField(blank=True, choices=[('A', 'SATA'), ('B', 'SAS'), ('C', 'SCSI'), ('D', 'SSD')], max_length=64, null=True, verbose_name='磁盘类型')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdbapi.server')),
            ],
        ),
    ]
