# Generated by Django 3.1 on 2020-08-13 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdbapi', '0002_auto_20200813_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='type',
            new_name='server_type',
        ),
    ]
