# Generated by Django 3.1 on 2020-08-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdbapi', '0003_auto_20200813_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='server',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
    ]
