# Generated by Django 3.1 on 2020-08-18 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdbapi', '0004_auto_20200813_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='disk_name',
            field=models.CharField(max_length=16, null=True, verbose_name='盘符'),
        ),
        migrations.AddField(
            model_name='server',
            name='disk_size',
            field=models.CharField(max_length=16, null=True, verbose_name='磁盘大小'),
        ),
        migrations.AlterField(
            model_name='servernetwork',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdbapi.server'),
        ),
    ]
