# Generated by Django 3.1 on 2020-08-18 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdbapi', '0005_auto_20200818_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='disk_name',
        ),
        migrations.RemoveField(
            model_name='server',
            name='disk_size',
        ),
        migrations.CreateModel(
            name='Mount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disk_name', models.CharField(max_length=16, null=True, verbose_name='盘符')),
                ('disk_size', models.CharField(max_length=16, null=True, verbose_name='磁盘大小')),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdbapi.server')),
            ],
        ),
    ]
