# Generated by Django 3.1 on 2020-08-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdbapi', '0006_auto_20200818_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='is_virtual',
            field=models.BooleanField(blank=True, default=False, verbose_name='是否是虚拟化'),
        ),
    ]
