# Generated by Django 3.1 on 2020-08-25 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdbapi', '0007_server_is_virtual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servernetwork',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nic', to='cmdbapi.server'),
        ),
    ]
