# Generated by Django 3.1 on 2020-10-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdbapi', '0010_auto_20200916_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='uuid',
            field=models.CharField(max_length=64, null=True, verbose_name='服务器唯一标识符'),
        ),
    ]
