"""
Django settings for cmdb project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'xd73ah+u!fn@&=3a4akbv$op2j-l-4ba%j53qjq89)w@3t+wsa'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'cmdbapi.apps.CmdbapiConfig',
    'cmdbweb.apps.CmdbwebConfig',
    'rbac.apps.RbacConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'rbac.middlewares.rbac.RbacMiddleware',
]

ROOT_URLCONF = 'cmdb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cmdb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'cmdb_new',
        'USER': 'cmdb',
        'PASSWORD': 'g4p8jl8S&ykg*^1',
        'HOST': '123.57.93.249',
        'PORT': '3306',
        'CONN_MAX_AGE': 30,
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-hans'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

# USE_TZ = True
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

# 静态文件相关配置
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# 用于指定url路径
MEDIA_URL = '/media/'
# 用于指定上传文件的存储路径
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# #################### 日志配置 #########################
# https://docs.djangoproject.com/zh-hans/3.1/topics/logging/
# 设置log目录
LOG_DIR = os.path.join(BASE_DIR, "logs")
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)

LOGGING = {
    "version": 1.0,
    # 设置日志格式
    "formatters": {
        # 详细的日志格式
        "standard": {
            "format": "%(asctime)s [%(threadName)s: %(thread)d]"
                        "%(pathname)s:%(funcName)s:%(lineno)d %(levelname)s - %(message)s"
        },
        # 简单的日志格式
        "simple": {
            "format": "%(asctime)s %(message)s"
        }
    },
    # 格式器
    "handlers": {
        # 终端处理器
        "console_handler": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "standard"
        },
        # 文件处理器 RotatingFileHandler 循环文件处理器
        "file_handler": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            # 指定路径的名字
            "filename": os.path.join(LOG_DIR, "backend.log"),
            "maxBytes": 1024*1024*1024,
            # 保存的备份数量
            "backupCount": 5,
            "formatter": "standard",
            "encoding": "utf8"
        },
        # 统计,产生文件
        "statistics_handler": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            # 指定路径的名字
            "filename": os.path.join(LOG_DIR, "statistics.log"),
            "maxBytes": 1024*1024*5,
            # 保存的备份数量
            "backupCount": 5,
            "formatter": "simple",
            "encoding": "utf8"
        }
    },
    "loggers": {
        # 日志的名字
        "django": {
            "handlers": ["console_handler", "file_handler"],
            "level": "DEBUG"
        },
        "statistics": {
            "handlers": ["statistics_handler"],
            "level": "DEBUG"
        }
    }
}


# ##################### 发送邮件配置 #######################
# 邮件服务器配置
EMAIL_HOST = 'smtp.qq.com'
EMAIL_PORT = 25
EMAIL_HOST_USER = '997083657@qq.com'
## 默认抄送地址
DEFAULT_CC_EMAIL = ("liangbingwen@comsenz-service.com", )
EMAIL_HOST_PASSWORD = 'owifoihsvjphbbhg'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_USE_SSL = False


# #################### redis 缓存配置 #####################
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://123.57.93.249:8099/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "PASSWORD": "ibwen_oo1122"
        }
    }
}

SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"


# #################### 权限相关配置 #######################
# 业务中的用户表
RBAC_USER_MODLE_CLASS = "cmdbweb.models.User"
# 权限在Session中存储的key
PERMISSION_SESSION_KEY = "cmdb_permission_url_list_key"
# 菜单在Session中存储的key
MENU_SESSION_KEY = "cmdb_permission_menu_key"

# 白名单
VALID_URL_LIST = [
    '/login/',
    '/admin/.*',
    '/api/*',
    '/media/*'
]

# 需要登录但无需权限的URL
NO_PERMISSION_LIST = [
    '/index/',
    '/logout/',
]

# 自动化发现路由中URL时, 排除的URL
AUTO_DISCOVER_EXCLUDE = [
    '/admin/.*',
    '/login/',
    '/logout/',
    '/index/',
]