# Generated by Django 3.1 on 2020-09-16 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdbweb', '0003_auto_20200916_1713'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='Group',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='department',
            new_name='group',
        ),
    ]
