# Generated by Django 3.1 on 2020-08-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='method',
            field=models.CharField(max_length=16, null=True, verbose_name='请求方法'),
        ),
    ]
