# Generated by Django 3.1 on 2020-08-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_permission_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=32, verbose_name='URL别名'),
        ),
    ]
