# Generated by Django 3.1 on 2020-08-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20200827_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='method',
        ),
        migrations.AddField(
            model_name='permission',
            name='action',
            field=models.CharField(max_length=16, null=True, verbose_name='请求要做什么操作,对应请求方法'),
        ),
    ]
